apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - default: https://github.com/CSCI-GA-2820-FA23-001/recommendations.git
      description: The URL to the git repo
      name: GIT_REPO
      type: string
    - default: 31-CD-to-OpenShift-Kubernetes
      description: The reference (branch or ref)
      name: GIT_REF
      type: string
    - default: '-vvv --processes=1 --run-coverage --minimum-coverage=95'
      description: Arguments for green testing
      name: GREEN_ARGS
      type: string
    - default: recommendations
      description: Name of the application
      name: APP_NAME
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest
      description: The name of the image to build
      name: IMAGE_NAME
      type: string
    - default: 'cluster-registry:32000/recommendations:latest'
      description: The name of the old image to build
      name: OLD_IMAGE_NAME
      type: string
    - default: >-
        https://recommendations-xh1131-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
      description: The base url to the microservice
      name: BASE_URL
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: pylint
      params:
        - name: image
          value: 'docker.io/rofrano/nyu-devops-base:fa23'
        - name: path
          value: service
        - name: requirements_file
          value: requirements.txt
        - name: args
          value: []
        - name: pip_conf_file
          value: pip.conf
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: testing
      params:
        - name: ARGS
          value: $(params.GREEN_ARGS)
        - name: SECRET_NAME
          value: postgres-creds
        - name: SECRET_KEY
          value: database_uri
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: green
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:00795fafdab9bbaa22cd29d1faa1a01e604e4884a2c935c1bf8e3d1f0ad1c084
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - pylint
        - testing
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy-image
      params:
        - name: old_image_name
          value: $(params.OLD_IMAGE_NAME)
        - name: image_name
          value: $(params.IMAGE_NAME)
        - name: manifest_dir
          value: k8s
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: deploy-image
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: behave
      params:
        - name: BASE_URL
          value: $(params.BASE_URL)
      runAfter:
        - deploy-image
      taskRef:
        kind: Task
        name: behave
      workspaces:
        - name: source
          workspace: pipeline-workspace